---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-stocks-simulated
  namespace: demo-stocks-simulated
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: stocks-simulated
  serviceName: demo
  template:
    metadata:
      labels:
        demo: stocks-simulated
    spec:
      containers:
        - image: DOCKER_IMAGE
          imagePullPolicy: Always
          name: demo
          ports:
            - containerPort: 9001
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi


