---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-stocks-simulated
  namespace: demo-stocks-simulated
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: stocks-simulated
  serviceName: demo
  template:
    metadata:
      labels:
        demo: stocks-simulated
    spec:
      volumes:
        - name: consumer-properties
          secret:
            secretName: consumer-properties
      containers:
        - image: DOCKER_IMAGE
          imagePullPolicy: Always
          name: demo
          args:
            - "-Dswim.config=/config/server.k8s.recon"
          volumeMounts:
            - mountPath: /secret/confluent
              name: consumer-properties
          ports:
            - containerPort: 9001
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
